name = "pihuw"
license = "BSD 3-clause"
licenselink = "https://github.com/mrmxf/pihuw/blob/main/LICENSE"
description = "A Hugo wrapper for PicnicCss"
homepage = "https://mrmxf.com"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.145.0"

[author]
  name = "Mr MXF"
  homepage = "https://mrmxf.com"
